Ultimate Packers Website/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Ultimate_Packers_Website.GlobalModels;
using Ultimate_Packers_Website.services;
using Ultimate_Packers_Website.ViewModels;

namespace Ultimate_Packers_Website
{
    public class ClientsController : Controller
    {
        private readonly WMSContext _context;
        private readonly IEmailSender _emailSender;

        public ClientsController(WMSContext context, IEmailSender emailSender)
        {
            _context = context;
            _emailSender = emailSender;
        }

        // GET: Clients
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var clients = _context.TblClients.Include(status => status.ClientStatus).ToListAsync();

            return View(await clients);
        }

        // GET: Clients/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = _context.TblClients.FirstOrDefault(c => c.ClientId == id);
            var BAdrr = _context.TblAddresses.FirstOrDefault(a => a.AddressId == client.ClientBillingAddressId);
            var SHAddr = _context.TblAddresses.FirstOrDefault(s => s.AddressId == client.ShippingAddressId);
            ViewData["ID"] = client.ClientId;

            ClientDetailsVM clientDetails = new ClientDetailsVM();
            clientDetails.LinkToImage = "";
            clientDetails.CompanyName = client.CompanyName;
            clientDetails.ClientName = client.FirstName +" "+client.LastName;
            clientDetails.BillingAddressLine1 = BAdrr.AddressLine1;
            clientDetails.BillingAddressLine2 = BAdrr.AddressLine2;
            clientDetails.BillingCity = BAdrr.City;
            clientDetails.BillingState = BAdrr.State;
            clientDetails.BillingZip = BAdrr.Zip;
            clientDetails.BillingCountry = BAdrr.Country;
            clientDetails.Phone = client.PhoneNumber;
            clientDetails.Email = client.EmailAddress;
            clientDetails.ShippingAddressLine1 = SHAddr.AddressLine1;
            clientDetails.ShippingAddressLine2 = SHAddr.AddressLine2;
            clientDetails.ShippingCity = SHAddr.City;
            clientDetails.ShippingState = SHAddr.State;
            clientDetails.ShippingZip = SHAddr.Zip;
            clientDetails.ShippingCountry = SHAddr.Country;

            if (clientDetails == null)
            {
                return NotFound();
            }

            return View(clientDetails);
        }

        // GET: Clients/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClientId,CompanyName,PhoneNumber,EmailAddress,FirstName,LastName,ClientBillingAddressId,ShippingAddressId,ClientStatusId")] TblClients tblClients)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tblClients);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tblClients);
        }

        // GET: Clients/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblClients = await _context.TblClients.FindAsync(id);
            if (tblClients == null)
            {
                return NotFound();
            }
            return View(tblClients);
        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ClientId,CompanyName,PhoneNumber,EmailAddress,FirstName,LastName,ClientBillingAddressId,ShippingAddressId,ClientStatusId")] TblClients tblClients)
        {
            if (id != tblClients.ClientId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tblClients);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TblClientsExists(tblClients.ClientId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tblClients);
        }

        // GET: Clients/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblClients = await _context.TblClients
                .FirstOrDefaultAsync(m => m.ClientId == id);
            if (tblClients == null)
            {
                return NotFound();
            }

            return View(tblClients);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tblClients = await _context.TblClients.FindAsync(id);
            _context.TblClients.Remove(tblClients);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TblClientsExists(int id)
        {
            return _context.TblClients.Any(e => e.ClientId == id);
        }
    }
}

Ultimate Packers Website/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Ultimate_Packers_Website.GlobalModels;

namespace Ultimate_Packers_Website.Controllers
{
    public class ItemsController : Controller
    {
        private readonly WMSContext _context;

        public ItemsController(WMSContext context)
        {
            _context = context;
        }

        // GET: Items
        public async Task<IActionResult> Index()
        {
            var wMSContext = _context.TblItems;//.Include(t => t.Client);.Include(t => t.ItemImageId);

            return View(await wMSContext.ToListAsync());
        }

        // GET: Items/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblItems = await _context.TblItems
                //.Include(t => t.Client)
                //.Include(t => t.ItemImageId)
                .FirstOrDefaultAsync(m => m.ItemId == id);
            if (tblItems == null)
            {
                return NotFound();
            }

            return View(tblItems);
        }

        // GET: Items/Create
        public IActionResult Create()
        {
            ViewData["ClientId"] = new SelectList(_context.TblClients, "ClientId", "ClientId");
            ViewData["ItemImageId"] = new SelectList(_context.TblItemImages, "ItemImageId", "ItemImageType");
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ItemId,ClientId,ItemImageId,ItemName,ItemNumber,Sku,Upc,Active")] TblItems tblItems)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tblItems);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClientId"] = new SelectList(_context.TblClients, "ClientId", "ClientId", tblItems.ClientId);
            ViewData["ItemImageId"] = new SelectList(_context.TblItemImages, "ItemImageId", "ItemImageType", tblItems.ItemImageId);
            return View(tblItems);
        }

        // GET: Items/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblItems = await _context.TblItems.FindAsync(id);
            if (tblItems == null)
            {
                return NotFound();
            }
            ViewData["ClientId"] = new SelectList(_context.TblClients, "ClientId", "ClientId", tblItems.ClientId);
            ViewData["ItemImageId"] = new SelectList(_context.TblItemImages, "ItemImageId", "ItemImageType", tblItems.ItemImageId);
            return View(tblItems);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ItemId,ClientId,ItemImageId,ItemName,ItemNumber,Sku,Upc,Active")] TblItems tblItems)
        {
            if (id != tblItems.ItemId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tblItems);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TblItemsExists(tblItems.ItemId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClientId"] = new SelectList(_context.TblClients, "ClientId", "ClientId", tblItems.ClientId);
            ViewData["ItemImageId"] = new SelectList(_context.TblItemImages, "ItemImageId", "ItemImageType", tblItems.ItemImageId);
            return View(tblItems);
        }

        // GET: Items/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblItems = await _context.TblItems
                //.Include(t => t.Client)
                .Include(t => t.ItemImageId)
                .FirstOrDefaultAsync(m => m.ItemId == id);
            if (tblItems == null)
            {
                return NotFound();
            }

            return View(tblItems);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tblItems = await _context.TblItems.FindAsync(id);
            _context.TblItems.Remove(tblItems);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TblItemsExists(int id)
        {
            return _context.TblItems.Any(e => e.ItemId == id);
        }
    }
}

Ultimate Packers Website/Views/Shared/AccountLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <link rel="icon" href="~/Images/Logo.ico" type="image/ico" />

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    
    <partial name="_LinksBundle" />
</head>
<body>

    @RenderBody()
    
    <partial name="_scriptsBundle" />
    @RenderSection("Scripts", false)
</body>
</html>

Ultimate Packers Website/Views/Shared/AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="~/Images/Logo.ico" type="image/ico" />

    <title>Ultimate Packers Admin Pannel </title>
   
    <partial name="_LinksBundle" />
</head>

<body>
    <!-- top navigation -->
    <div class="top_nav navbar-fixed-top">
        <div class="nav_menu">
            <nav>
                <div class="nav toggle">
                    <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                </div>
                <ul class="nav navbar-nav navbar-right">
                    <li class="">

                    </li>
                </ul>
            </nav>
        </div>
    </div>
    <!-- /top navigation -->
    <div>
        <br />
        <br />
        <br />
        @RenderBody()
    </div>

    <partial name="_scriptsBundle" />

    @RenderSection("Scripts", required: false)
</body>
</html>

Ultimate Packers Website/Views/Shared/_Header.cshtml
<!-- top navigation -->
<div class="top_nav navbar-fixed-top">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <partial name="_LoginPartial" />
            </li>
            </ul>
        </nav>
    </div>
</div>
<!-- /top navigation -->

Ultimate Packers Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="~/Images/Logo.ico" type="image/ico" />
   
    <title>Ultimate Packers @ViewBag.Title </title>
    <partial name="_LinksBundle" />
</head>

<body class="nav-md">
    <div class="container body">
        <div class="main_container">

            <!--Side nav-->
            <partial name="_SideNav.cshtml" />

            <!--Header navbar-->
            <partial name="_Header.cshtml" />

            <div class="right_col" role="main">
                <br /><br /><br />
                @RenderBody()
            </div>
        </div>
    </div>

   <partial name="_scriptsBundle" />
    @RenderSection("Scripts", required: false)
</body>
</html>

Ultimate Packers Website/Views/Shared/_LinksBundle.cshtml
<link href="~/Template/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="~/Template/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
<!-- NProgress -->
<link href="~/Template/vendors/nprogress/nprogress.css" rel="stylesheet">
<!-- iCheck -->
<link href="~/Template/vendors/iCheck/skins/flat/green.css" rel="stylesheet">
<!-- bootstrap-progressbar -->
<link href="~/Template/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
<!-- JQVMap -->
<link href="~/Template/vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet" />
<!-- bootstrap-daterangepicker -->
<link href="~/Template/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">
<!-- Custom Theme Style -->
<link href="~/Template/build/css/custom.min.css" rel="stylesheet">
<!--Data Tables-->
<link href="~/DataTables/jquery.dataTables.css" rel="stylesheet" />
<!--w3 schools-->
<link href="~/CSS/w3-StyleSheet.css" rel="stylesheet" />
<!--Custom Styles-->
<link href="~/CSS/site.css" rel="stylesheet" />

Ultimate Packers Website/Views/Shared/_SideNav.cshtml
<div class="col-md-3 left_col menu_fixed">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
            <a asp-action="Index" asp-controller="Clients" class="site_title"><span>Ultimate Packers</span></a>
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile clearfix">
            <div class="profile_pic">
                <img src="~/Images/defaultProfile.png" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
                <span>Welcome,</span>
                <h2>John Doe</h2>
            </div>
        </div>
        <!-- /menu profile quick info -->
        <br />
        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu ">
            <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                    <li>
                        <a><i class="fa fa-user"></i> Clients <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a asp-action="Index" asp-controller="Clients">Client List</a></li>
                            <li><a asp-action="Create" asp-controller="Clients">Create New</a></li>
                            <li><a href="index3.html">Dashboard3</a></li>
                        </ul>
                    </li>
                    <li>
                        <a><i class="fa fa-edit"></i> Inbound Orders <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a asp-action="Index" asp-controller="IoHeaders">Inbound Orders List</a></li>
                            <li><a asp-action="Create" asp-controller="IOHeaders">Create Inbound Order</a></li>
                        </ul>
                    </li>
                    <li>
                        <a><i class="fa fa-table"></i>Outbound Orders<span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="tables.html">List</a></li>
                            <li><a href="tables_dynamic.html">Add Outbound Order</a></li>
                        </ul>
                    </li>
                    <li>
                        <a><i class="fa fa-desktop"></i> Products<span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a asp-action="Index" asp-controller="Items">Product List</a></li>
                            <li><a href="media_gallery.html">Listings</a></li>
                            <li><a href="typography.html">Typography</a></li>
                            <li><a href="icons.html">Icons</a></li>
                            <li><a href="glyphicons.html">Glyphicons</a></li>
                            <li><a href="widgets.html">Widgets</a></li>
                            <li><a href="invoice.html">Invoice</a></li>
                            <li><a href="inbox.html">Inbox</a></li>
                            <li><a href="calendar.html">Calendar</a></li>
                        </ul>
                    </li>

                    <li>
                        <a><i class="fa fa-bar-chart-o"></i> Data Presentation <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="chartjs.html">Chart JS</a></li>
                            <li><a href="chartjs2.html">Chart JS2</a></li>
                            <li><a href="morisjs.html">Moris JS</a></li>
                            <li><a href="echarts.html">ECharts</a></li>
                            <li><a href="other_charts.html">Other Charts</a></li>
                        </ul>
                    </li>
                    <li>
                        <a><i class="fa fa-clone"></i>Layouts <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="fixed_sidebar.html">Fixed Sidebar</a></li>
                            <li><a href="fixed_footer.html">Fixed Footer</a></li>
                        </ul>
                    </li>
                </ul>
            </div>

        </div>
        <!-- /sidebar menu -->
        <!-- /menu footer buttons -->
        <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a  href="/Identity/Account/Login" data-toggle="tooltip" data-placement="top" title="Logout">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
        </div>
        <!-- /menu footer buttons -->
    </div>
</div>

Ultimate Packers Website/Views/Shared/_scriptsBundle.cshtml
 <!-- jQuery -->
<script src="~/Template/vendors/jquery/dist/jquery-2.2.4.min.js"></script>
<!--Data Tables-->
<script src="~/DataTables/DataTables-1.10.18/js/jquery.dataTables.min.js"></script>
<!-- Bootstrap -->
<script src="~/Template/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- FastClick -->
<script src="~/Template/vendors/fastclick/lib/fastclick.js"></script>
<!-- NProgress -->
<script src="~/Template/vendors/nprogress/nprogress.js"></script>
<!-- Chart.js -->
<script src="~/Template/vendors/Chart.js/dist/Chart.min.js"></script>
<!-- gauge.js -->
<script src="~/Template/vendors/gauge.js/dist/gauge.min.js"></script>
<!-- bootstrap-progressbar -->
<script src="~/Template/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
<!-- iCheck -->
<script src="~/Template/vendors/iCheck/icheck.min.js"></script>
<!-- Skycons -->
<script src="~/Template/vendors/skycons/skycons.js"></script>
<!-- Flot -->
<script src="~/Template/vendors/Flot/jquery.flot.js"></script>
<script src="~/Template/vendors/Flot/jquery.flot.pie.js"></script>
<script src="~/Template/vendors/Flot/jquery.flot.time.js"></script>
<script src="~/Template/vendors/Flot/jquery.flot.stack.js"></script>
<script src="~/Template/vendors/Flot/jquery.flot.resize.js"></script>
<!-- Flot plugins -->
<script src="~/Template/vendors/flot.orderbars/js/jquery.flot.orderBars.js"></script>
<script src="~/Template/vendors/flot-spline/js/jquery.flot.spline.min.js"></script>
<script src="~/Template/vendors/flot.curvedlines/curvedLines.js"></script>
<!-- DateJS -->
<script src="~/Template/vendors/DateJS/build/date.js"></script>
<!-- JQVMap -->
<script src="~/Template/vendors/jqvmap/dist/jquery.vmap.js"></script>
<script src="~/Template/vendors/jqvmap/dist/maps/jquery.vmap.world.js"></script>
<script src="~/Template/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>
<!-- bootstrap-daterangepicker -->
<script src="~/Template/vendors/moment/min/moment.min.js"></script>
<script src="~/Template/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>
<!-- Custom Theme Scripts -->
<script src="~/Template/Build/js/custom.min.js"></script>