Ultimate Packers Website/ViewModels/LPDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ultimate_Packers_Website.GlobalModels;

namespace Ultimate_Packers_Website.ViewModels
{
    public class LPDetailsViewModel
    {
        public IEnumerable<TblDamagedItems> DamagedItems { get; set; }
        public IEnumerable<TblInventoryDetails> InventoryDetails { get; set; }
        public IEnumerable<TblInventoryTransaction> InventoryTransactions { get; set; }
    }
}

Ultimate Packers Website/ViewComponents/AdminDashboard/AdminViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ultimate_Packers_Website.GlobalModels;
using Ultimate_Packers_Website.ViewModels;

namespace Ultimate_Packers_Website.ViewComponents.AdminDashboard
{
    public class AdminViewComponent : ViewComponent
    {
        private readonly WMSContext _context;

        public AdminViewComponent(WMSContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync(string Component)
        {
            if (Component == "Locations")
            {
                var list = _context.TblLocations.ToList();
                var viewModel = new AdminViewModel { Locations = list };

                return View("Locations", viewModel);
            }

            else if (Component == "LicensePlates")
            {
                var list = _context.TblLicencePlates.ToList();
                var viewModel = new AdminViewModel { LicencePlates = list };

                return View("LicensePlates", viewModel);
            }
            
            return View("NotFound");
        }
    }
}

Ultimate Packers Website/ViewComponents/InventoryDetails/InventoryDetailsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ultimate_Packers_Website.GlobalModels;
using Ultimate_Packers_Website.ViewModels;

namespace Ultimate_Packers_Website.ViewComponents.DamagedItems
{
    public class InventoryDetailsViewComponent : ViewComponent
    {
        private readonly WMSContext _context;

        public InventoryDetailsViewComponent(WMSContext context) => _context = context;

        public async Task<IViewComponentResult> InvokeAsync(int id, string type)
        {
            if (type == "Damaged")
            {
                var damaged = await _context.TblDamagedItems.Where(i => i.Lpid == id).ToListAsync();
                var viewModel = new LPDetailsViewModel { DamagedItems = damaged };

                return View("Damaged", viewModel);
            }
            else if (type == "Inventory")
            {
                var inventory = _context.TblInventoryDetails.Where(i => i.Lpid == id).ToList();
                var viewModel = new LPDetailsViewModel { InventoryDetails = inventory };

                return View("Inventory", viewModel);
            }

            return View("NotFound");
        }
    }
}

Ultimate Packers Website/Views/Admin/Dashboard.cshtml
@model Ultimate_Packers_Website.ViewModels.AdminViewModel
@{
    ViewData["Title"] = "Dashboard";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h1><strong>Admin Dashboard</strong></h1>

<div>@await Component.InvokeAsync("Admin", new { Component = "Locations" })</div>

<div>@await Component.InvokeAsync("Admin", new { Component = "LicensePlates"})</div>

Ultimate Packers Website/Views/Admin/LPDetails.cshtml
@model Ultimate_Packers_Website.ViewModels.LPDetailsViewModel
@{
    ViewData["Title"] = "License Plates Details";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
    var id = ViewBag.id;
}

<a class="btn btn-primary" asp-action="Dashboard"><< Back</a>
<a id="modal" href="#modal-container" role="button" class="btn btn-primary" data-toggle="modal">
    Change Location
</a>

<h1>What is in LP# @id ?</h1>

<div>@await Component.InvokeAsync("InventoryDetails", new { id = ViewBag.id, type = "Inventory" })</div>

<div>@await Component.InvokeAsync("InventoryDetails", new { id = ViewBag.id, type = "Damaged" })</div>

<div class="modal" id="modal-container" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document" id="body">

    </div>

</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#modal').click(function () {
                $.ajax({
                    url: '/Admin/ChangeLocation/'+@id,
                    method: 'GET',
                    dataType: 'html',
                    success: function (content) {
                        $('#body').html(content);
                    },
                    error: function (err) {
                        alert(err.status)
                    }
                })
            })
        })
    </script>
}

Ultimate Packers Website/Views/Admin/LocationDetails.cshtml
@model IEnumerable<Ultimate_Packers_Website.GlobalModels.TblLicencePlates>
@{
    ViewData["Title"] = "Location Details";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h1>Location Details</h1>

<div class="col-md-6 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            <h2>License Plates For Location ID# @ViewBag.ID<small></small></h2>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li>
                    <a class="close-link"><i class="fa fa-close"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <table id="" class="table table-striped table-bordered"> <!--add id="Databales" to get feutures-->
                <thead>
                    <tr>
                        <th>LP ID</th>
                        <th>LP Name</th>
                        <th>Date Created</th>
                        <th>Location ID</th>
                        <th>LP Type</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Lpid</td>
                            <td>@item.Lpname</td>
                            <td>@item.DateCreated</td>
                            <td>@item.LocationId</td>
                            <td>@item.Lptype</td>
                            <td><i class="fa fa-edit"></i></td>
                        </tr>
                    }
                </tbody>
            </table>
            <a class="btn btn-primary" asp-action="Dashboard"><< Back</a>
        </div>
    </div>
</div>